Done Sprint 4
f4natic/Sprint_4 pull request #1
Opened 2023-09-06 12:20 UTC by f4natic

2023-09-07 19:36 UTC, pavel-ulan requested changes
Привет. Работа неплохая, молодец. Есть ряд критичных замечаний, есть пара нестрашных, но стоит обратить на них внимание, что бы не повторять такого в будущем.
Я все расписал - правь и присылай еще раз =)

2023-09-07 19:36 UTC, pavel-ulan commented on src/test/java/ru/yandex/practicum/base/Constants.java
> +    private Constants(){}
**можно лучше**
Два зачем: 
зачем ты final-изируешь класс?
и зачем тебе тут конструктор (тем более пустой)?
Если коротко - это лишнее. Я еще могу понять final класс тут (хотя опять же, как правило классы с константами это просто классы), предположим это архитектурный задел на будущее. но пустой конструктор - для чего? У тебя константы, они static, они прогружаются сразу и не требуют инициализации класса, у них такой механизм работы.

2023-09-07 19:36 UTC, pavel-ulan commented on src/test/java/ru/yandex/practicum/AboutImportantTest.java
> +        new MainPage(driver).acceptCookie();
**можно лучше**
не критично, но так тоже не принято делать. Добавь одну строчку - создай объект класса и дальше работай с ним.

2023-09-07 19:36 UTC, pavel-ulan commented on src/test/java/ru/yandex/practicum/AboutImportantTest.java
> +        assertEquals("На восьмом вопросе не показывается ответ", true, infoPage.answerEightShowText());
**надо исправить**
тут ты покушаешься на фундаментальные правила тестирования =)
"Один тест - одна проверка."  - т.е. не усложняй.
Серьезно. Если у тебя ошибка только во втором вопросе, то весь тест навернется и проверять придется после исправления все. А PM ждет результатов и давит на тебя сроками. Оно тебе надо?
А так, вместо "у нас не работает блок FAQ" ты сможешь сказать, что "из 8 элементов у нас отвалился один". В целом, можно жить дальше.
Так что разнеси на отдельные тесты или сделай параметризованный тест.
П.с.
Иногда когда делаешь несколько проверок в тесте (если это подразумевается самим тестом), такой подход допустим. Но даже там обычно используют softAssertations что бы собрать максимально возможную информацию.

2023-09-07 19:36 UTC, pavel-ulan commented on src/test/java/ru/yandex/practicum/AcceptanceTest.java
**хорошо**
Ну, такой условный тест на тест... ок, валидно.

2023-09-07 19:36 UTC, pavel-ulan commented on src/test/java/ru/yandex/practicum/OrderTest.java
> +        assertEquals(true, orderSuccessPage.orderExist());
**надо исправить**
Прям жестко захардкодил все тестовые данные =)
А представь, что к тебе будут приходить каждый день с просьбой поменять тестового пользователя? или вообще дадут файл с 100 юзеров и скажут проверить. Будешь каждого подменять в коде?
Тестовые данные никогда не хардкодят в тестах. Если ты уверен, что они не поменяются - сделай константы на эти данные, создай класс модель и сделай объект с тестовыми данными, сделай генератор рандомных данных если они не важны, ну или сделай провайдер, который передает эти данные из внешнего файла (что лучше всего). В общем варианты есть - выбери подходящий себе.

2023-09-08 03:51 UTC, f4natic commented on src/test/java/ru/yandex/practicum/base/Constants.java
> +    private Constants(){}
Конструктор не пустой, а приватный, для того что бы нельзя было создать инстанс это класса, а final для того, что бы нельзя было наследоваться от него. Защита от "глупых людей", но ладно уберу

2023-09-08 04:42 UTC, f4natic commented on src/test/java/ru/yandex/practicum/page/CheckoutPage.java
> +}
Удалил

2023-09-08 04:42 UTC, f4natic commented on src/test/java/ru/yandex/practicum/page/AboutImportantPage.java
> +        return false;
переписал на id

2023-09-08 04:58 UTC, f4natic commented on src/test/java/ru/yandex/practicum/AboutImportantTest.java
> +        new MainPage(driver).acceptCookie();
исправил

2023-09-08 04:58 UTC, f4natic commented on src/test/java/ru/yandex/practicum/AboutImportantTest.java
> +        assertEquals("На восьмом вопросе не показывается ответ", true, infoPage.answerEightShowText());
Переписал на Parametrized

2023-09-08 04:59 UTC, f4natic commented on src/test/java/ru/yandex/practicum/OrderTest.java
> +        assertEquals(true, orderSuccessPage.orderExist());
Исправил

2023-09-10 16:59 UTC, pavel-ulan commented on src/test/java/ru/yandex/practicum/base/Constants.java
> +    private Constants(){}
погоди, блок "можно лучше" на то и отдельный блок не обязателеный к исправлению, так что тут могут быть спорные моменты.
вариант с "ограничить возможность наследоваться" вполне валиден и оправдан, хотя лично я считаю это too much. Как правило достаточно простого класса с константами и на нескольких проектах я уже встречал именно такую реализацию. Остальное считается само собой разумеющимся (не наследоваться и не создавать инстансов). В конце концов полностью обезопасить проект невозможно

2023-09-10 17:05 UTC, pavel-ulan requested changes
я вижу твои комменты но не вижу, что бы ты вкоммитил какие-то изменения. проверь не остались ли они в локальном репе, после запушь изменения

2023-09-11 18:00 UTC, pavel-ulan approved these changes
Да, очень даже неплохо 👍

2023-09-11 18:00 UTC, pavel-ulan commented on src/test/java/ru/yandex/practicum/base/ButtonType.java
> +}
**хорошо**
хорошее решение
(в исполнении с switch/case конечно не очень, но решение использовать enum - хорошее)

2023-11-06 12:28 UTC, closed without merging